import dns from "node:dns";
dns.setServers(['8.8.8.8','8.8.4.4'])


import { Montserrat, Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
   variable : "--font-poppins",
   subsets :["latin"],
   weight:["400", "500","700","600"]
})

export const montserrat = Montserrat({
   variable : "--font-montserrat",
   subsets :["latin"],
   weight:["400", "500","700","600"]
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${poppins.className}h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        </body>
    </html>
  );
}
